// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "sekund",
      seconds: "sekunder",
      minute: "minut",
      minutes: "minutter",
      hour: "time",
      hours: "timer",
      day: "dag",
      days: "dage",
      month: "måned",
      months: "måneder",
      year: "år",
      years: "år"
    },
    prefixes: {
      lt: "mindre end",
      about: "ca.",
      over: "over",
      almost: "næsten",
      ago: ""
    },
    suffix: " siden"
  };

}).call(this);
