// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "segundo",
      seconds: "segundos",
      minute: "minuto",
      minutes: "minutos",
      hour: "hora",
      hours: "horas",
      day: "dia",
      days: "dias",
      month: "mês",
      months: "meses",
      year: "ano",
      years: "anos"
    },
    prefixes: {
      lt: "menos de um",
      about: "aproximadamente",
      over: "pouco mais de",
      almost: "quase",
      ago: ""
    },
    suffix: " atrás"
  };

}).call(this);
