// Generated by CoffeeScript 1.6.1
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "秒",
      seconds: "秒",
      minute: "分",
      minutes: "分",
      hour: "時間",
      hours: "時間",
      day: "日",
      days: "日",
      month: "ヶ月",
      months: "ヶ月",
      year: "年",
      years: "年"
    },
    prefixes: {
      lt: "約 1",
      about: "大体",
      over: "",
      almost: "",
      ago: ""
    },
    suffix: '前'
  };

}).call(this);
