// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "segon",
      seconds: "segons",
      minute: "minut",
      minutes: "minuts",
      hour: "hora",
      hours: "hores",
      day: "dia",
      days: "dies",
      month: "mes",
      months: "mesos",
      year: "any",
      years: "anys"
    },
    prefixes: {
      lt: "fa menys d\'un",
      about: "prop de",
      over: "més de",
      almost: "gairebé",
      ago: "fa "
    },
    suffix: ""
  };

}).call(this);
