// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "segundo",
      seconds: "segundos",
      minute: "minuto",
      minutes: "minutos",
      hour: "hora",
      hours: "horas",
      day: "día",
      days: "días",
      month: "mes",
      months: "meses",
      year: "año",
      years: "años"
    },
    prefixes: {
      lt: "hace menos de un",
      about: "cerca de",
      over: "poco más de",
      almost: "casi",
      ago: "hace "
    },
    suffix: ""
  };

}).call(this);
