// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "seconde",
      seconds: "secondes",
      minute: "minute",
      minutes: "minutes",
      hour: "heure",
      hours: "heures",
      day: "jour",
      days: "jours",
      month: "mois",
      months: "mois",
      year: "an",
      years: "ans"
    },
    prefixes: {
      lt: "moins d'un",
      about: "environ",
      over: "plus de ",
      almost: "presque",
      ago: "il y a "
    },
    suffix: ""
  };

}).call(this);
