// Generated by CoffeeScript 1.6.1
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "秒",
      seconds: "秒",
      minute: "分钟",
      minutes: "分钟",
      hour: "小时",
      hours: "小时",
      day: "天",
      days: "天",
      month: "月",
      months: "月",
      year: "年",
      years: "年"
    },
    prefixes: {
      lt: "不到 1",
      about: "大约",
      over: "超过",
      almost: "接近",
      ago: ""
    },
    suffix: "之前"
  };

}).call(this);
