// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.timeago.defaults.lang = {
    units: {
      second: "second",
      seconds: "seconds",
      minute: "minute",
      minutes: "minutes",
      hour: "hour",
      hours: "hours",
      day: "day",
      days: "days",
      month: "month",
      months: "months",
      year: "year",
      years: "years"
    },
    prefixes: {
      lt: "less than a",
      about: "about",
      over: "over",
      almost: "almost",
      ago: ""
    },
    suffix: " ago"
  };

}).call(this);
